#idempiereEnv.properties
#Fri May 08 03:05:59 PET 2026
ADEMPIERE_DB_SERVER=localhost
ADEMPIERE_APPS_SERVER=0.0.0.0
ADEMPIERE_DB_VERSION=2026-03-09
ADEMPIERE_FTP_PASSWORD=user@host.com
IDEMPIERE_JAVA_OPTIONS=-Xmx2048M
ADEMPIERE_KEYSTORECODEALIAS=idempiere
ADEMPIERE_DATE_VERSION=2026-03-09
ADEMPIERE_DB_NAME=idempiere14
JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
ADEMPIERE_DB_USER=adempiere
ADEMPIERE_MAIN_VERSION=Release 14
ADEMPIERE_DB_EXISTS=N
ADEMPIERE_MAIL_SERVER=0.0.0.0
ADEMPIERE_CERT_ORG_UNIT=iDempiere Github
ADEMPIERE_KEYSTOREWEBALIAS=idempiere
ADEMPIERE_CERT_COUNTRY=US
ADEMPIERE_CERT_LOCATION=myTown
ADEMPIERE_CERT_STATE=CA
ADEMPIERE_DB_URL=jdbc\:postgresql\://localhost\:5432/idempiere14
ADEMPIERE_WEB_PORT=8080
ADEMPIERE_MAIL_USER=
ADEMPIERE_KEYSTORE=/home/nextcollege/BDeveloper/idempiere-dev-setup-14/idempiere/org.idempiere.p2/target/products/org.adempiere.server.product/linux/gtk/x86_64/jettyhome/etc/keystore
ADEMPIERE_DB_PATH=postgresql
ADEMPIERE_FTP_SERVER=localhost
ADEMPIERE_WEB_ALIAS=nextcollege-G751JT
ADEMPIERE_MAIL_UPDATED=
ADEMPIERE_ADMIN_EMAIL=
ADEMPIERE_KEYSTOREPASS=OBF\:1uh41zly1qw01vu11ym71ym71vv91qxq1zlk1ugm
ADEMPIERE_FTP_USER=anonymous
ADEMPIERE_SSL_PORT=8443
ADEMPIERE_DB_PORT=5432
ADEMPIERE_CERT_CN=idempiere.org
ADEMPIERE_DB_SYSTEM_USER=
ADEMPIERE_FTP_PREFIX=my
ADEMPIERE_DB_TYPE=PostgreSQL
ADEMPIERE_CERT_ORG=iDempiere
IDEMPIERE_HOME=/home/nextcollege/BDeveloper/idempiere-dev-setup-14/idempiere/org.idempiere.p2/target/products/org.adempiere.server.product/linux/gtk/x86_64
